### ISSUE TITLE
Out of bounds bits cause errors

### ISSUE THREAD

**Issue by jhnstrk** [MrElectrify/better_bitset#2]
The test case looks like this:
```
        constexpr BitSet<4> f(0b11111111);
        static_assert(f.all() == true);
        static_assert(f.any() == true);
        static_assert(f.none() == false);
        static_assert(f.count() == 4);
        static_assert(f.first_one() == 0);
        static_assert(f.first_zero() == 4);}
```

The high bits are set in the input, causing the `count`  and `first_zero` methods to fail. `first_zero` is easy to fix (return N instead of pos). 
Fixing count needs either: 
- to mask the input in the constructor, to force upper bits to zero.
- to treat the last element in the storage specially when accumulating.
- subtract high bits from the result.
The first seems easier, but depends whether preserving the high bit information is important. (reset wipes it anyway).

**Comment by MrElectrify** [comment]
Good catch, I'll probably take the first approach
